//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ebList
    {
        public Nullable<int> city08 { get; set; }
        public Nullable<int> cylinders { get; set; }
        public Nullable<double> displ { get; set; }
        public string drive { get; set; }
        public Nullable<int> engId { get; set; }
        public string eng_dscr { get; set; }
        public Nullable<int> fuelCost08 { get; set; }
        public string fuelType { get; set; }
        public string fuelType1 { get; set; }
        public Nullable<int> highway08 { get; set; }
        public string id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string trany { get; set; }
        public string VClass { get; set; }
        public Nullable<int> year { get; set; }
        public string youSaveSpend { get; set; }
        public string trans_dscr { get; set; }
        public string tCharger { get; set; }
        public string sCharger { get; set; }
    }
}
